import Script from "next/script";
import Link from "next/link";

export default function Head() {
  return (
    <>
      <title>Next 13</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <Script
        defer
        src="https://kit.fontawesome.com/dfc91c03ad.js"
        crossOrigin="anonymous"
      ></Script>
    </>
  );
}
